[package]
name = "alliance"
version = "0.1.0"
edition = "2018"
authors = ["Hjate C. Nannestad"]
description = "WIP contact me if you want the name"
licenses = ["MIT"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
